### ISSUE TITLE
[Feature Request] Add device IP address to attributes

### ISSUE THREAD

**Issue by guice** [cyberjunky/home-assistant-arpscan_tracker#1]
I noticed ARP Scanner is not adding the IP Address of a device to it's attributes, e.g.:

### nmap_tracker
```yaml
source_type: router
latitude: 38.80801184504557
longitude: -104.84741628170015
gps_accuracy: 0
scanner: NmapDeviceScanner
ip: 192.168.0.97
friendly_name: Ecovacs DEEBOT
icon: mdi:robot-vacuum
```

### arpscan_tracker
```yaml
source_type: router
latitude: 38.80801184504557
longitude: -104.84741628170015
gps_accuracy: 0
scanner: ArpScanDeviceScanner
friendly_name: Ecovacs DEEBOT
icon: mdi:robot-vacuum
```

It would be nice if it can add the device's current IP address. It does return in the arp table:
```
Address                  HWtype  HWaddress           Flags Mask            Iface
192.168.0.98             ether   44:07:0b:67:6b:43   C                     eno1
192.168.0.38             ether   64:16:66:22:27:16   C                     eno1
192.168.0.15             ether   30:fd:38:67:ea:2c   C                     eno1
192.168.0.60             ether   44:07:0b:c4:4b:21   C                     eno1
192.168.0.86                     (incomplete)                              eno1
[...]
```
