### ISSUE TITLE
track_new_devices: false is ignored

### ISSUE THREAD

**Issue by Dmattiazzi** [cyberjunky/home-assistant-arpscan_tracker#12]
the configuration "track_new_devices: false" is ignored and in "known_devices.yaml" the devices are all "track: true"

**Comment by cyberjunky** [comment]
@Dmattiazzi sorry for the very late reply, I just tested it, this works here:

```
device_tracker:
  - platform: arpscan_tracker
    scan_options: --interface=eth0 192.168.1.0/24 -g
    new_device_defaults:
      track_new_devices: False
```

```
780f77509abc:
  name: 780f77509abc
  mac: 78:0F:77:50:9A:BC
  icon:
  picture:
  track: false

3693bb370abc:
  name: 3693bb370abc
  mac: 36:93:BB:37:0A:BC
  icon:
  picture:
  track: false
```
